#!/usr/bin/env bash
# ============================================================
# AI Research Refinery - Security Setup Script
# Generates self-signed SSL certs, random passwords, API keys
# and writes a secure .env file with proper permissions.
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SECRETS_DIR="$PROJECT_DIR/secrets"
CERTS_DIR="$SECRETS_DIR/certs"
ENV_FILE="$PROJECT_DIR/.env.secure"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ----- helper: generate random string -----
gen_password() {
    local len=${1:-32}
    openssl rand -base64 "$len" | tr -d '/+=' | head -c "$len"
}

gen_hex() {
    local len=${1:-32}
    openssl rand -hex "$len" | head -c "$len"
}

# ----- pre-flight checks -----
if ! command -v openssl &>/dev/null; then
    error "openssl is required but not installed."
    exit 1
fi

if [ -d "$SECRETS_DIR" ]; then
    warn "Secrets directory already exists: $SECRETS_DIR"
    read -rp "Overwrite existing secrets? (y/N) " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        info "Aborted. Existing secrets unchanged."
        exit 0
    fi
    rm -rf "$SECRETS_DIR"
fi

# ----- create directory structure -----
info "Creating secrets directory structure..."
mkdir -p "$CERTS_DIR"

# ----- generate SSL certificates -----
info "Generating self-signed CA certificate..."
openssl genrsa -out "$CERTS_DIR/ca.key" 4096 2>/dev/null
openssl req -new -x509 -sha256 -days 3650 \
    -key "$CERTS_DIR/ca.key" \
    -out "$CERTS_DIR/ca.crt" \
    -subj "/C=US/ST=Local/L=Local/O=AIRefinery/CN=Refinery-CA" 2>/dev/null

info "Generating server certificate for internal services..."
openssl genrsa -out "$CERTS_DIR/server.key" 2048 2>/dev/null

# SAN config for all internal service names
cat > "$CERTS_DIR/san.cnf" <<'SANEOF'
[req]
distinguished_name = req_dn
req_extensions = v3_req
prompt = no

[req_dn]
C  = US
ST = Local
L  = Local
O  = AIRefinery
CN = refinery-server

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1  = localhost
DNS.2  = postgres
DNS.3  = redis
DNS.4  = minio
DNS.5  = backend
DNS.6  = llm-embed
DNS.7  = llm-reason
DNS.8  = monitor-agent
DNS.9  = healing-agent
DNS.10 = auditor
DNS.11 = orchestrator
DNS.12 = researcher
DNS.13 = mcp-server
DNS.14 = worker-crawler
DNS.15 = worker-chunking
DNS.16 = worker-embedding
DNS.17 = worker-evaluation
DNS.18 = worker-extraction
DNS.19 = worker-conflict
IP.1   = 127.0.0.1
SANEOF

openssl req -new -sha256 \
    -key "$CERTS_DIR/server.key" \
    -out "$CERTS_DIR/server.csr" \
    -config "$CERTS_DIR/san.cnf" 2>/dev/null

openssl x509 -req -sha256 -days 365 \
    -in "$CERTS_DIR/server.csr" \
    -CA "$CERTS_DIR/ca.crt" \
    -CAkey "$CERTS_DIR/ca.key" \
    -CAcreateserial \
    -out "$CERTS_DIR/server.crt" \
    -extensions v3_req \
    -extfile "$CERTS_DIR/san.cnf" 2>/dev/null

# Clean up CSR and serial
rm -f "$CERTS_DIR/server.csr" "$CERTS_DIR/ca.srl"

info "SSL certificates generated."

# ----- generate passwords and keys -----
info "Generating random passwords and API keys..."

POSTGRES_PASSWORD="$(gen_password 32)"
REDIS_PASSWORD="$(gen_password 32)"
MINIO_ROOT_USER="minio-$(gen_password 12)"
MINIO_ROOT_PASSWORD="$(gen_password 40)"
API_KEY="rfn-$(gen_hex 32)"
API_KEY_2="rfn-$(gen_hex 32)"

# ----- write .env.secure -----
info "Writing secure environment file: $ENV_FILE"

cat > "$ENV_FILE" <<ENVEOF
# ===========================================================
# AI Research Refinery - Secure Environment Configuration
# Generated by setup-security.sh on $(date -Iseconds)
# DO NOT commit this file to version control!
# ===========================================================

# --- GPU Configuration ---
GPU_EMBED=${GPU_EMBED:-all}
GPU_REASON=${GPU_REASON:-all}

# --- PostgreSQL ---
POSTGRES_USER=refinery
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://refinery:${POSTGRES_PASSWORD}@postgres:5432/refinery

# --- Redis ---
REDIS_PASSWORD=${REDIS_PASSWORD}

# --- MinIO ---
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# --- API Authentication ---
# Comma-separated list of valid API keys for the backend
API_KEYS=${API_KEY},${API_KEY_2}

# --- Orchestrator ---
ORCHESTRATOR_AUTO_RESEARCH=true
ORCHESTRATOR_CYCLE=60
AUDIT_INTERVAL=1800
MAX_URLS_PER_HOUR=30
MAX_PER_DOMAIN_PER_HOUR=5
ENVEOF

# ----- write Redis ACL file -----
info "Generating Redis configuration..."
cat > "$SECRETS_DIR/redis.conf" <<REOF
# Redis security configuration
requirepass ${REDIS_PASSWORD}
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
rename-command DEBUG ""

# Memory
maxmemory 512mb
maxmemory-policy allkeys-lru

# Networking
bind 0.0.0.0
protected-mode yes
tcp-backlog 511
timeout 300
REOF

# ----- set file permissions -----
info "Setting file permissions..."

# Secrets directory: owner-only
chmod 700 "$SECRETS_DIR"
chmod 700 "$CERTS_DIR"

# Private keys: owner read-only
chmod 600 "$CERTS_DIR/ca.key"
chmod 600 "$CERTS_DIR/server.key"

# Certs and config: owner read-only
chmod 644 "$CERTS_DIR/ca.crt"
chmod 644 "$CERTS_DIR/server.crt"
chmod 644 "$CERTS_DIR/san.cnf"
chmod 600 "$SECRETS_DIR/redis.conf"

# Env file: owner read-only
chmod 600 "$ENV_FILE"

# ----- summary -----
echo ""
info "=========================================="
info "  Security setup complete!"
info "=========================================="
echo ""
info "Generated files:"
echo "  $CERTS_DIR/ca.key         (CA private key)"
echo "  $CERTS_DIR/ca.crt         (CA certificate)"
echo "  $CERTS_DIR/server.key     (Server private key)"
echo "  $CERTS_DIR/server.crt     (Server certificate)"
echo "  $SECRETS_DIR/redis.conf   (Redis auth config)"
echo "  $ENV_FILE                 (Environment secrets)"
echo ""
info "API Keys (save these somewhere safe):"
echo "  Key 1: ${API_KEY}"
echo "  Key 2: ${API_KEY_2}"
echo ""
info "Next steps:"
echo "  1. Review $ENV_FILE"
echo "  2. Copy GPU settings from your existing .env if needed"
echo "  3. Start with: docker compose --env-file .env.secure up --build"
echo ""
warn "IMPORTANT: Never commit secrets/ or .env.secure to git!"
echo ""
